"""core.events — Observer Pattern.

Exposição pública do sistema de eventos.
"""
from .emitter import EventEmitter
from .events import (
    NEW_MESSAGE, BROADCAST_RECEIVED, ACK_RECEIVED, MESSAGE_STATUS,
    POW_STARTED, POW_PROGRESS, POW_COMPLETED, POW_CANCELLED,
    CONNECTION_CHANGE, PEER_CONNECTED, PEER_DISCONNECTED,
    INVENTORY_UPDATE,
    CONTACT_ADDED, CONTACT_REMOVED,
    IDENTITY_CREATED, IDENTITY_UPDATED, IDENTITY_REMOVED,
    SUBSCRIBED, LOGGED, BROADCAST_SENT,
    LEGACY_MAP,
)

__all__ = [
    'EventEmitter',
    'NEW_MESSAGE', 'BROADCAST_RECEIVED', 'ACK_RECEIVED', 'MESSAGE_STATUS',
    'POW_STARTED', 'POW_PROGRESS', 'POW_COMPLETED', 'POW_CANCELLED',
    'CONNECTION_CHANGE', 'PEER_CONNECTED', 'PEER_DISCONNECTED',
    'INVENTORY_UPDATE',
    'CONTACT_ADDED', 'CONTACT_REMOVED',
    'IDENTITY_CREATED', 'IDENTITY_UPDATED', 'IDENTITY_REMOVED',
    'SUBSCRIBED', 'LOGGED', 'BROADCAST_SENT',
    'LEGACY_MAP',
]
